### ISSUE TITLE
Limit ToC headings to class "sutta-title", implement secondary ToC

### ISSUE THREAD

**Issue by janwadolowski** [suttacentral/publications#59]
Current implementation creates table of contents from all headings of some level range (by default 1-6). We need to implement additional filter described in this issue: [https://github.com/suttacentral/suttacentral/issues/2363](https://github.com/suttacentral/suttacentral/issues/2363).

* If edition data specifies `"main-toc-depth": "all"` -> we make ToC ofheadings from `<h1>` to `<hX>` with class `class='sutta-title'`
* If edition data specifies `"main-toc-depth": "{number}"` -> we make ToC of all headings from `<h1>` to `<h{number}>`, regardless of class `class='sutta-title'` AND only for levels h1-h{number}
* If edition data specifies `"secondary-toc": true` -> we make a secodary ToC for all lowest level headings in the main ToC (if main ToC is h1-h2 under each `<h2>` we add a secondary ToC of headings in range h3-hX with class `class='sutta-title'`. `class='sutta-title'` is a hard limit, anything below that is considered a "subheading" and shouldn't be included in either main or secondary ToC.

**Comment by sujato** [comment]
Jan, this is not correct. :crying_cat_face: 

Let me specify it once more and try to be as clear and explicit as I can. 

- `"main-toc-depth": "all"` means "all heading levels from `<h1>` down to and including whatever heading level has `class='sutta-title'`."
- `"main-toc-depth": "2"` means "`<h1>` and `<h2>`. 
     - When the `main-toc-depth` is specified, ignore `sutta-title`. `sutta-title` only applies in `main-toc` and `secondary-toc` as a cutoff point, the lowest level that the toc goes to. But when the `main-toc-depth` is specified, there is no need for this, as the cutoff point is explicit.
- `"secondary-toc": true` means "start at whatever heading level comes after the `main-toc`and  build a set of separate ToCs, one for every entry in the main ToC, down to and including whatever level has `sutta-title`.

"Subheadings" are internal headings inside suttas. They **never** go in a ToC. Here is what I said in the spec in #2363, maybe I wasn't clear enough. :laughing: I probably need more emojis!

- ⚠ **Subheadings are not added to the toc.**
- ⚠ **Never include subheadings in toc.**
- no subheading is added to ToC

Again, let me repeat once more, to make sure we are on the same page.

- An HTML document is structured by `<hX>` tags.
- The titles of suttas are identified by the addition of `class='sutta-title'` to the `<hX>` tag, whatever level it may be.
- By convention, "heading" is what we call all  `<hX>` tags starting with `<h1>` down to and including whatever level has `sutta-title` . 
- By convention, "subheading" is what we call any `<hX>` tag that is at a lower level than `sutta-title`.
    - So if we have `<h4 class='sutta-title'>` then all `<h5>` and `<h6>` are called "subheadings".
- All headings are included in `main-toc` or one of the `secondary-toc`.
- No subheading is ever in any ToC. Not in `main-toc`, not in `secondary-toc`. 

Let me give some examples.

Assume an HTML doc with the following heading structure.

```
<h1>part title</h1>
<h2>chapter title</h2>
<h3 class="sutta-title">sutta title</h3>
<h4>sutta subheading</h4>
<h4>another sutta subheading</h4>
<h3 class="sutta-title">another sutta title</h3>
<h2>another chapter title</h2>
<h3 class="sutta-title">extra sutta title</h3>
<h4>sutta subheading</h4>
<h4>another sutta subheading</h4>
<h3 class="sutta-title">further sutta title</h3>
```

If we have `"main-toc-depth": "all"` the ToC would be:

```
<nav>
    <ol>
        <li>
            Part title
            <ol>
                <li>
                    chapter title
                    <ol>
                        <li>sutta title</li>
                        <li>another sutta title</li>
                    </ol>
                </li>
                <li>
                    another chapter title
                    <ol>
                        <li>extra sutta title</li>
                        <li>further sutta title</li>
                    </ol>
                </li>
            </ol>
        </li>
    </ol>
</nav>
```

If we have `"main-toc-depth": "2"` the main ToC would be:

```
<nav>
    <ol>
        <li>
            Part title
            <ol>
                <li>chapter title</li>
                <li>another chapter title</li>
            </ol>
        </li>
    </ol>
</nav>
```

If we have `"secondary-toc": true`, then we know that the `main-toc` finishes at `<h2>` because this is specified (`"main-toc-depth": "2"`). So, each time an `<h2>` appears in the text, we insert a secondary table of contents. 

```
<h2>chapter title</h2>
<nav>
    <ol>
        <li>sutta title</li>
        <li>another sutta title</li>
    </ol>
</nav>

(…. text ….)

<h2>another chapter title</h2>
<nav>
    <ol>
        <li>extra sutta title</li>
        <li>further sutta title</li>
    </ol>
</nav>
```

The secondary toc, in other words, *continues the table of contents from the main-toc*. A reader see the large divisions in the main toc, goes to the place in the text where that part starts, and there they see a secondary-toc that specifies the content of that section.

**Comment by janwadolowski** [comment]
Thank you for that, I was actually going to write a comment under the mentioned ticket #2363 with some questions but your response and examples clarified all of them.
Worry not, even though I partially misunderstood the information you provided my yesterday's work on implementation of this ticket is still useful as I was implementing some helper functions for the process and made some rework in code of base parser to avoid code repetition between all parsers down the road.

I will correct the description of the issue after our standup meeting to reflect your actual requirements and avoid misinforming anyone who might come across this issue in the future. Sorry for that confusion.
